// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzWISUD7S_H_FUqCeGtTo6twL6ZJuaQsw',
    appId: '1:544535348624:web:e695a3715d922fd216df15',
    messagingSenderId: '544535348624',
    projectId: 'task-manager-app-c32ae',
    authDomain: 'task-manager-app-c32ae.firebaseapp.com',
    storageBucket: 'task-manager-app-c32ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO2E4LljTqoD3THLTO3DKaCxnzfTH9vms',
    appId: '1:544535348624:android:7e92df68cf6eca3316df15',
    messagingSenderId: '544535348624',
    projectId: 'task-manager-app-c32ae',
    storageBucket: 'task-manager-app-c32ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEXPSE6kWwRbg-iGGxq7RO45j02Q67kU8',
    appId: '1:544535348624:ios:ef1b4e6197426bf516df15',
    messagingSenderId: '544535348624',
    projectId: 'task-manager-app-c32ae',
    storageBucket: 'task-manager-app-c32ae.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEXPSE6kWwRbg-iGGxq7RO45j02Q67kU8',
    appId: '1:544535348624:ios:ef1b4e6197426bf516df15',
    messagingSenderId: '544535348624',
    projectId: 'task-manager-app-c32ae',
    storageBucket: 'task-manager-app-c32ae.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzWISUD7S_H_FUqCeGtTo6twL6ZJuaQsw',
    appId: '1:544535348624:web:076115e3cac036a616df15',
    messagingSenderId: '544535348624',
    projectId: 'task-manager-app-c32ae',
    authDomain: 'task-manager-app-c32ae.firebaseapp.com',
    storageBucket: 'task-manager-app-c32ae.appspot.com',
  );
}
